name: 'Verify Changes'

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Go
        uses: actions/setup-go@v5

      - name: Build Check
        run: |
          make test

